import Provider from './provider';
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <div className="min-h-screen bg-background text-foreground antialiased">
            <Header />
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
